<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <MicrosoftPlaywrightVersion Condition="'$(MicrosoftPlaywrightVersion)' == ''">1.61.0</MicrosoftPlaywrightVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Playwright" Version="$(MicrosoftPlaywrightVersion)" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>
</Project>
