using Xunit;

namespace SpyBrowser.Cursory.Tests;
public sealed class GeneratorTests
{
    [Fact] public void Pcg64RawDrawsMatchPinnedNumpyVector(){var rng=new Internal.RandomSampler(new Internal.Pcg64((UInt128)1));var expected=new[]{0.5118216247002567,0.9504636963259353,0.14415961271963373,0.9486494471372439,0.31183145201048545};foreach(var value in expected)Assert.Equal(value,rng.Uniform(0,1));}
    [Fact] public void EndpointsAndTimingsAreValid(){var t=CursoryTrajectoryGenerator.Generate(new(4,8),new(220,135),new(){Seed=42});Assert.Equal(new(4,8),t.Points[0]);Assert.Equal(new(220,135),t.Points[^1]);Assert.Equal(0,t.Timings[0]);Assert.Equal(t.Points.Count,t.Timings.Count);Assert.All(t.Points,p=>Assert.True(double.IsFinite(p.X)&&double.IsFinite(p.Y)));Assert.All(t.Timings.Zip(t.Timings.Skip(1)),x=>Assert.True(x.Second>=x.First));}
    [Fact] public void RepeatedSeedIsDeterministic(){var a=CursoryTrajectoryGenerator.Generate(new(-3.25,12),new(8.5,-90),new(){Seed=UInt128.MaxValue});var b=CursoryTrajectoryGenerator.Generate(new(-3.25,12),new(8.5,-90),new(){Seed=UInt128.MaxValue});Assert.Equal(a.Points,b.Points);Assert.Equal(a.Timings,b.Timings);}
    [Fact] public void DegenerateMotionIsSinglePoint(){var a=new TrajectoryPoint(1.5,-2);var t=CursoryTrajectoryGenerator.Generate(a,a);Assert.Equal(new[]{a},t.Points);Assert.Equal(new[]{0d},t.Timings);}
    [Theory][InlineData(double.NaN,0,1,1)][InlineData(double.PositiveInfinity,0,1,1)] public void RejectsNonfinite(double x,double y,double ex,double ey)=>Assert.Throws<ArgumentOutOfRangeException>(()=>CursoryTrajectoryGenerator.Generate(new(x,y),new(ex,ey)));
    [Fact] public void MatchesPinnedUpstreamFixtures(){using var doc=System.Text.Json.JsonDocument.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"Fixtures","parity.json")));foreach(var c in doc.RootElement.GetProperty("cases").EnumerateArray()){var input=c.GetProperty("input");var s=input.GetProperty("start");var e=input.GetProperty("end");var t=CursoryTrajectoryGenerator.Generate(new(s[0].GetDouble(),s[1].GetDouble()),new(e[0].GetDouble(),e[1].GetDouble()),new(){Frequency=input.GetProperty("frequency").GetDouble(),FrequencyRandomizer=input.GetProperty("frequencyRandomizer").GetDouble(),Seed=(UInt128)input.GetProperty("seed").GetUInt64(),Directness=input.GetProperty("directness").GetDouble()});var expected=c.GetProperty("points").EnumerateArray().ToArray();var times=c.GetProperty("timings").EnumerateArray().ToArray();Assert.Equal(expected.Length,t.Points.Count);Assert.Equal(times.Length,t.Timings.Count);for(int i=0;i<times.Length;i++){Assert.Equal(times[i].GetDouble(),t.Timings[i]);Assert.InRange(Math.Abs(expected[i][0].GetDouble()-t.Points[i].X),0,1e-9);Assert.InRange(Math.Abs(expected[i][1].GetDouble()-t.Points[i].Y),0,1e-9);}}}
    [Fact] public async Task SharedDatasetSupportsConcurrentCalls(){var all=await Task.WhenAll(Enumerable.Range(0,32).Select(i=>Task.Run(()=>CursoryTrajectoryGenerator.Generate(new(i,0),new(200,i+1),new(){Seed=(UInt128)i}))));Assert.All(all,t=>Assert.Equal(t.Points.Count,t.Timings.Count));}
}
